name: Publish on Netlify
on: [push]
jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:    
    - uses: actions/checkout@v2

    - name: install
      run: sudo apt-get install asciidoctor -y

    - name: Compile
      run: make
    
    - name: Publish
      uses: netlify/actions/cli@master
      with:
            publish-dir: './dist'
            production-branch: main
            enable-pull-request-comment: false
            enable-commit-comment: true
            overwrites-pull-request-comment: true
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
